# Generated by Django 3.2.12 on 2022-07-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0054_auto_20220709_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrecord',
            old_name='is_acceptable',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='reviewrecord',
            old_name='user',
            new_name='reviewer',
        ),
        migrations.RemoveField(
            model_name='reviewrecord',
            name='task',
        ),
        migrations.AddField(
            model_name='reviewrecord',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.job'),
        ),
    ]
