# Generated by Django 3.2.12 on 2022-07-12 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0056_auto_20220712_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assign_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
