# Generated by Django 3.2.12 on 2022-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0057_auto_20220712_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assign_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
